import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';
import './LegalPages.css';

function TermsOfService() {
  const [locale, setLocale] = useState('fr');

  useEffect(() => {
    const storedLocale = localStorage.getItem('iris-locale');
    if (storedLocale === 'en' || storedLocale === 'fr') {
      setLocale(storedLocale);
    }
  }, []);

  const content = {
    fr: {
      title: "Conditions Générales d'Utilisation et de Vente",
      lastUpdated: 'Dernière mise à jour : Septembre 2026',
      intro: "Les présentes conditions régissent l'accès et l'utilisation de l'application Iris. En créant un compte, vous acceptez pleinement ces conditions.",
      sections: [
        {
          title: "1. Objet",
          text: "Iris est une application de bureau (Windows, macOS) qui se connecte à votre boîte mail (Gmail et/ou Outlook) pour catégoriser automatiquement vos emails et proposer des actions associées — confirmation de rendez-vous en un clic dans vos calendriers connectés (Google, Apple, Outlook), génération de résumés, de réponses et de plans d'action assistée par intelligence artificielle."
        },
        {
          title: "2. Compte utilisateur",
          text: "La création d'un compte nécessite une adresse email valide, vérifiée avant plein accès au service. Vous êtes seul responsable de la confidentialité de vos identifiants et garantissez être le titulaire légitime des comptes tiers (Gmail, Outlook, calendriers) que vous connectez à Iris."
        },
        {
          title: "3. Limites du service",
          text: "La catégorisation des emails et les créneaux de rendez-vous suggérés sont générés par un traitement automatisé (analyse de langage et intelligence artificielle) : ils peuvent comporter des erreurs. Vous restez seul responsable de vérifier l'exactitude d'un rendez-vous ou d'un contenu généré avant de vous y fier. Le service dépend de la disponibilité des services tiers connectés (Google, Microsoft, Apple, fournisseur d'IA) et peut être affecté par leurs interruptions."
        },
        {
          title: "4. Données personnelles",
          text: "Le traitement de vos données est détaillé dans notre Politique de Confidentialité. Vous disposez des droits d'accès, de rectification, d'effacement et de portabilité prévus par le RGPD."
        },
        {
          title: "5. Tarification",
          text: "Iris propose les offres suivantes (voir la page Tarifs pour le détail des fonctionnalités incluses). Offres individuelles : 3 mois (19,99 € au total, soit 6,66 €/mois), 6 mois (34,99 € au total, soit 5,83 €/mois), 12 mois (64,99 € au total, soit 5,41 €/mois). Offres entreprise (B2B2E, facturation annuelle) : 100 salariés (11 988 €/an, soit 9,99 €/mois/salarié, + 5 salariés offerts), 250 salariés (23 970 €/an, soit 7,99 €/mois/salarié, + 7% de salariés offerts), 1000 salariés (59 880 €/an, soit 4,99 €/mois/salarié, + 10% de salariés offerts). Toutes les offres payantes bénéficient d'une garantie satisfait ou remboursé de 90 jours."
        },
        {
          title: "6. Résiliation",
          text: "Vous pouvez supprimer votre compte à tout moment depuis les paramètres de l'application. Nous pouvons suspendre ou résilier un compte en cas d'usage frauduleux ou de non-respect des présentes conditions."
        },
        {
          title: "7. Contact",
          text: "Pour toute question relative à ces conditions, contactez-nous à irisapp42@outlook.com."
        }
      ],
      back: "Retour à l'accueil",
      copyright: "© 2025-2026 Iris. Tous droits réservés."
    },
    en: {
      title: "Terms of Use and Sale",
      lastUpdated: 'Last updated: September 2026',
      intro: "These terms govern access to and use of the Iris application. By creating an account, you fully accept these terms.",
      sections: [
        {
          title: "1. Purpose",
          text: "Iris is a desktop application (Windows, macOS) that connects to your mailbox (Gmail and/or Outlook) to automatically categorize your emails and suggest related actions — one-click meeting confirmation across your connected calendars (Google, Apple, Outlook), and AI-assisted summaries, replies, and action plans."
        },
        {
          title: "2. User account",
          text: "Creating an account requires a valid, verified email address. You are solely responsible for the confidentiality of your credentials and warrant that you are the legitimate holder of any third-party accounts (Gmail, Outlook, calendars) you connect to Iris."
        },
        {
          title: "3. Service limitations",
          text: "Email categorization and suggested meeting slots are generated by automated processing (language analysis and artificial intelligence) and may contain errors. You remain solely responsible for verifying the accuracy of any appointment or generated content before relying on it. The service depends on the availability of connected third-party services (Google, Microsoft, Apple, AI provider) and may be affected by their outages."
        },
        {
          title: "4. Personal data",
          text: "The processing of your data is detailed in our Privacy Policy. You have the rights of access, rectification, erasure, and portability under GDPR."
        },
        {
          title: "5. Pricing",
          text: "Iris offers the following plans (see the Pricing page for full feature details). Individual plans: 3 months (€19.99 total, €6.66/month), 6 months (€34.99 total, €5.83/month), 12 months (€64.99 total, €5.41/month). Business plans (B2B2E, billed annually): 100 employees (€11,988/yr, €9.99/month/employee, +5 employees free), 250 employees (€23,970/yr, €7.99/month/employee, +7% employees free), 1000 employees (€59,880/yr, €4.99/month/employee, +10% employees free). All paid plans include a 90-day money-back guarantee."
        },
        {
          title: "6. Termination",
          text: "You may delete your account at any time from the application's settings. We may suspend or terminate an account in case of fraudulent use or breach of these terms."
        },
        {
          title: "7. Contact",
          text: "For any question about these terms, contact us at irisapp42@outlook.com."
        }
      ],
      back: "Back to Home",
      copyright: "© 2025-2026 Iris. All rights reserved."
    }
  };

  const t = content[locale];

  return (
    <div className="legal-page-container">
      <header className="legal-header">
        <Link to="/" className="legal-logo">Iris</Link>
        <Link to="/" className="back-home-btn">
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
            <line x1="19" y1="12" x2="5" y2="12"></line>
            <polyline points="12 19 5 12 12 5"></polyline>
          </svg>
          {t.back}
        </Link>
      </header>

      <main className="legal-card">
        <h1 className="legal-title">{t.title}</h1>
        <div className="legal-date">{t.lastUpdated}</div>

        <p className="legal-intro">{t.intro}</p>

        {t.sections.map((section, idx) => (
          <section key={idx} className="legal-section">
            <h2>{section.title}</h2>
            <p>{section.text}</p>
          </section>
        ))}

        <footer className="legal-footer">
          {t.copyright}
        </footer>
      </main>
    </div>
  );
}

export default TermsOfService;
